version: '3'
 
services:

    php:
        build:
            context: ./build/php
        ports:
            - 9000:9000
 
    nginx:
        image: nginx:1.14.0
        ports:
            - 8080:80
        volumes:
            - /home/osboxes/share/public:/usr/share/nginx/html
        depends_on:
            - php
 
    # mysql:
    #     image: mysql:5.7
    #     ports:
    #         - 3306:3306
    #     depends_on:
    #         - php
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}