version: '3.3'

services:
   nginx:
     build:
      context: ./nginx
      port:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/srv
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_HOST: 127.0.0.1
       MYSQL_ROOT_PASSWORD: wp
       MYSQL_DATABASE: wp
       MYSQL_USER: wp
       MYSQL_PASSWORD: wp

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wp_data:/home/osboxes/share/wordpress
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wp
       WORDPRESS_DB_PASSWORD: wp
volumes:
    db_data:
    wp_data: