version: '3'
 
services:

    php-fpm:
        build:
            context: ./build/php
        volumes:
            - /home/osboxes/share/docker/config/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        networks:
            - backend

    nginx:
        image: nginx:1.14.0
        ports:
            - 8080:80
        volumes:
            - /home/osboxes/share/docker/config/nginx:/etc/nginx/conf.d
            - /home/osboxes/share/public:/usr/share/nginx/html
            - /home/osboxes/share/logs/error.log:/var/log/nginx/error.log
            - /home/osboxes/share/logs/access.log:/var/log/nginx/access.log
        depends_on:
            - php-fpm
        networks:
            - backend
 
    # mysql:
    #     image: mysql:5.7
    #     ports:
    #         - 3306:3306
    #     depends_on:
    #         - php
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
    backend:
        external: true