version: '3'

# Docker와 맵핑할 볼륨은 현재 /home/ubuntu/Docker에 있다.(Amazon EC2 인스턴스 이용하여 clone한 상태)
# 다른 경로를 원한다면 볼륨에서 : 앞을 전부 바꿔주도록 하자.

services:
    php-fpm:
        build:
            context: ./build/php
        volumes:
            - /home/madforre/dev/madforre/Docker/config/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - /home/madforre/dev/madforre/Docker/logs/php-fpm:/var/log/nginx
            - /home/madforre/dev/public:/usr/share/nginx/html
        networks:
            - backend
        expose: 
            - "9000"

    nginx:
        image: nginx:1.14.0
        ports:
            - 80:80
        volumes:
            - /home/madforre/dev/madforre/Docker/config/nginx:/etc/nginx/conf.d
            - /home/madforre/dev/madforre/public:/usr/share/nginx/html
            - /home/madforre/dev/madforre/Docker/logs/nginx/error.log:/var/log/nginx/error.log
            - /home/madforre/dev/madforre/Docker/logs/nginx/access.log:/var/log/nginx/access.log
        depends_on:
            - php-fpm
        networks:
            - backend
 
    # mysql:
    #     image: mysql:5.7
    #     ports:
    #         - 3306:3306
    #     depends_on:
    #         - php
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${MYSQL_DATABASE}
    #         MYSQL_USER: ${MYSQL_USER}
    #         MYSQL_PASSWORD: ${MYSQL_PASSWORD}

# 사용자 지정 네트워크를 만들어 사용한다.
networks:
    backend:
        external: true